version: '3.0'
services:
  pg_superset_demo:
    image: pg_superset_demo:latest
    restart: always
  superset_demo:
    image: superset_demo:latest
    restart: always
    ports:
      - "8088:8088"
    links:
      - pg_superset_demo
