version: '2'
services:
  pg-demo-data:
    image: pg-demo-data:latest
    container_name: pg-demo-data
    ports:
      - "5432:5432"
    volumes:
      - ./.demo-data/postgres:/var/lib/postgresql/data
    restart: always
  superset-demo:
    image: superset-demo:latest
    container_name: superset-demo
    restart: always
    ports:
      - "8088:8088"
    links:
      - pg-demo-data
    volumes:
      - ./.demo-data/superset:/superset
volumes:
  pg-demo-data:
    external: false
  superset-demo:
    external: false

